sudo: required
services:
  - docker

before_install:
  - docker build -t vkingmaker/birdboard .
script:
  - docker run vkingmaker/birdboard vendor/bin/phpunit

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vkingmaker/birdboard

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Bd"
  env: "Bb-env"
  bucket_name: "elasticbeanstalk-us-east-1-933606557740"
  bucket_path:  "Bd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
