version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'birdboard'
      MYSQL_USER: 'birdboard'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3307:3306'
  webserver:
    build: .
    ports: 
      - 8080:80
