version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: 'birdboard'
      MYSQL_USER: 'birdboard'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3307:3306'
  webserver:
    build: .
    ports:
      - 8080:80
    environment:
      DB_HOST: db
      DB_PORT:  3306
      DB_DATABASE: birdboard
      DB_USERNAME: birdboard
      DB_PASSWORD: password
      APP_KEY: base64:aHlbY1fMQgXoCKvflfXtfI1XydwxWZliiKOhFmzs44s=

volumes:
  dbdata:

